workspace 'TotalCross'

use_modular_headers!

platform :ios, '12.1'
target 'TotalCross' do
  project 'TotalCross.xcodeproj'
  pod 'FirebaseMessaging', '10.8.0'
  pod "youtube-ios-player-helper", "~> 1.0.2"
end

target 'tcvm' do
  project 'tcvm.xcodeproj'
  pod 'FirebaseMessaging', '10.8.0'
  pod "youtube-ios-player-helper", "~> 1.0.2"
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    puts "#{target.name}"
    target.build_configurations.each do |config|
      # Force CocoaPods targets to always build for x86_64
      config.build_settings['ARCHS[sdk=iphonesimulator*]'] = 'x86_64'
    end
  end
end
