/*********************************************************************************
 *  TotalCross Software Development Kit - Litebase                               *
 *  Copyright (C) 2000-2011 SuperWaba Ltda.                                      *
 *  All Rights Reserved                                                          *
 *                                                                               *
 *  This library and virtual machine is distributed in the hope that it will     *
 *  be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of    *
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.                         *
 *                                                                               *
 *********************************************************************************/



// Generated by Byacc/j

package litebase;

/**
 * BYACC/J Semantic Value for parser: LitebaseParser. This class provides some of the functionality of the yacc/C 'union' directive.
 */
class LitebaseParserVal
{
   /**
    * Integer value of this 'union'.
    */
   int ival;

   /**
    * String value of this 'union'.
    */
   String sval;

   /**
    * Object value of this 'union'.
    */
   Object obj;
}
