// Copyright (C) 2026 Amalgam Solucoes em TI Ltda
//
// SPDX-License-Identifier: LGPL-2.1-only
package tc.tools.converter;

import java.io.IOException;
import java.lang.reflect.Constructor;
import java.lang.reflect.Method;
import java.lang.reflect.Modifier;
import java.net.URI;
import java.nio.charset.StandardCharsets;
import java.nio.file.FileSystem;
import java.nio.file.FileSystemNotFoundException;
import java.nio.file.FileSystems;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import java.util.Set;
import java.util.TreeSet;
import java.util.stream.Stream;

import org.objectweb.asm.Type;

/** Generates a derived index of host-JDK methods supported by the device model. */
public final class DeployedJavaApiManifestGenerator {
  private DeployedJavaApiManifestGenerator() {
  }

  public static List<String> entriesFor(Class<?> hostClass) {
    String owner = hostClass.getName().replace('.', '/');
    if (!Modifier.isPublic(hostClass.getModifiers())
        || !DeployedJavaApiValidator.isPlatformOwner(owner)) {
      return Collections.emptyList();
    }

    Set<String> entries = new TreeSet<String>();
    for (Constructor<?> constructor : hostClass.getConstructors()) {
      String descriptor = Type.getConstructorDescriptor(constructor);
      addIfSupported(entries, owner, "<init>", descriptor);
    }
    for (Method method : hostClass.getMethods()) {
      if (!Modifier.isPublic(method.getModifiers())) {
        continue;
      }
      String descriptor = Type.getMethodDescriptor(method);
      addIfSupported(entries, owner, method.getName(), descriptor);
    }
    return Collections.unmodifiableList(new ArrayList<String>(entries));
  }

  private static void addIfSupported(Set<String> entries, String owner, String name, String descriptor) {
    MethodDeclarationResolver.Resolution resolution =
        MethodDeclarationResolver.resolve(owner, name, descriptor);
    if (!resolution.deviceClassFound || !resolution.deviceMemberFound) {
      return;
    }
    String device = resolution.deviceOwner == null ? "-" : resolution.deviceOwner;
    String declaration = resolution.declarationOwner == null ? owner : resolution.declarationOwner;
    entries.add(owner + "#" + name + descriptor
        + "\tdeclaration=" + declaration + "\tdevice=" + device);
  }

  public static List<String> generate() throws IOException {
    MethodDeclarationResolver.beginConversionRun();
    Set<String> entries = new TreeSet<String>();
    FileSystem jrt = jrtFileSystem();
    Path modules = jrt.getPath("/modules");
    try (Stream<Path> paths = Files.walk(modules)) {
      paths.filter(Files::isRegularFile)
          .filter(path -> path.toString().endsWith(".class"))
          .forEach(path -> addClassEntries(entries, modules, path));
    }
    return new ArrayList<String>(entries);
  }

  private static void addClassEntries(Set<String> entries, Path modules, Path classFile) {
    Path relative = modules.relativize(classFile);
    if (relative.getNameCount() < 2) {
      return;
    }
    String classPath = relative.subpath(1, relative.getNameCount()).toString().replace('\\', '/');
    if ((!classPath.startsWith("java/") && !classPath.startsWith("javax/"))
        || classPath.endsWith("module-info.class")
        || classPath.endsWith("package-info.class")) {
      return;
    }
    String className = classPath.substring(0, classPath.length() - ".class".length()).replace('/', '.');
    try {
      Class<?> hostClass = Class.forName(className, false, ClassLoader.getPlatformClassLoader());
      entries.addAll(entriesFor(hostClass));
    } catch (LinkageError | ClassNotFoundException | SecurityException ignored) {
      // Some JRT implementation classes are intentionally not loadable through
      // the platform class loader. They cannot be part of the host-facing API.
    }
  }

  private static FileSystem jrtFileSystem() throws IOException {
    URI uri = URI.create("jrt:/");
    try {
      return FileSystems.getFileSystem(uri);
    } catch (FileSystemNotFoundException e) {
      return FileSystems.newFileSystem(uri, Collections.<String, Object>emptyMap());
    }
  }

  public static void write(Path output) throws IOException {
    List<String> lines = new ArrayList<String>();
    lines.add("# Generated by DeployedJavaApiManifestGenerator.");
    lines.add("# Do not edit manually; MethodDeclarationResolver is the source of truth.");
    lines.add("# Format: owner#name(descriptor)return<TAB>declaration=...<TAB>device=...");
    lines.addAll(generate());
    Files.createDirectories(output.toAbsolutePath().getParent());
    Files.write(output, lines, StandardCharsets.UTF_8);
  }

  public static void main(String[] args) throws Exception {
    Path output = args.length == 0
        ? Paths.get("build/generated/deployed-java-api.txt")
        : Paths.get(args[0]);
    write(output);
    System.out.println("Generated deployed Java API manifest: " + output.toAbsolutePath());
  }
}
