/*********************************************************************************
 *  TotalCross Software Development Kit                                          *
 *  Copyright (C) 2003 Fabian Kroeher                                            *
 *  Copyright (C) 2003-2012 SuperWaba Ltda.                                      *
 *  All Rights Reserved                                                          *
 *                                                                               *
 *  This library and virtual machine is distributed in the hope that it will     *
 *  be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of    *
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.                         *
 *                                                                               *
 *  This file is covered by the GNU LESSER GENERAL PUBLIC LICENSE VERSION 3.0    *
 *  A copy of this license is located in file license.txt at the root of this    *
 *  SDK or can be downloaded here:                                               *
 *  http://www.gnu.org/licenses/lgpl-3.0.txt                                     *
 *                                                                               *
 *********************************************************************************/



package totalcross.pim.ce.builtin;
/**
 * represents a collection of IAppointments
 * @author Fabian Kroeher (fabian@kroeher.net)
 *
 */
public class IAppointments extends IObjects
{
   /**
    * create a new instance of IAppointments and fills it with newly created instances
    * of IAppointment which are generated by reading out the native String which comes
    * from CeIoBuiltIn.dll by calling the superclass constructor of IObject
    * @param nativeString the native String (as StringExt) from CeIoBuiltIn.dll
    */
   public IAppointments(StringExt nativeString)
   {
      super(nativeString);
   }
   /* (non-Javadoc)
   * @see pimal.pocketpc.builtin.IObjects#newObject(pimal.pocketpc.builtin.StringExt)
   */
   public IObject newObject(StringExt nativeString)
   {
      return new IAppointment(nativeString);
   }
   /**
    * returns the IAppointment at the given index
    * @param position the index of the IAppointment to be returned
    * @return the IAppointment  at the given index
    */
   public IAppointment iAppointmentAt(int position)
   {
      return (IAppointment)objects.items[position];
   }
}
