project 'TotalCross.xcodeproj'

# Uncomment the next line to define a global platform for your project
platform :ios, '7.0'

target 'TotalCross' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for TotalCross
  pod 'Firebase/Core', '~> 4.0.2'

end
