workspace 'TotalCross'

# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'

target 'TotalCross' do
  project 'TotalCross.xcodeproj'
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for TotalCross
  pod 'Firebase/Core', '4.3.0'
  pod 'Firebase/Messaging', '4.3.0'
  pod 'FirebaseInstanceID', '2.0.4'
  pod "youtube-ios-player-helper", "~> 0.1.4"
end

target 'tcvm' do
  project 'tcvm.xcodeproj'

  pod 'Firebase/Core', '4.3.0'
  pod 'Firebase/Messaging', '4.3.0'
  pod 'FirebaseInstanceID', '2.0.4'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    puts "#{target.name}"
  end
end