// Copyright (C) 2026 Amalgam Solucoes em TI Ltda
//
// SPDX-License-Identifier: LGPL-2.1-only

package tc.tools.converter.modernjava;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertTrue;
import static org.junit.jupiter.api.Assumptions.assumeTrue;

import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.Locale;
import java.util.Optional;

import javax.tools.ToolProvider;

import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;

import tc.tools.converter.GlobalConstantPool;
import tc.tools.converter.J2TC;
import tc.tools.converter.bytecode.ByteCode;
import tc.tools.converter.java.JavaClass;
import tc.tools.converter.tclass.TCClass;
import tc.tools.converter.tclass.TCCode;
import tc.tools.converter.tclass.TCMethod;

class TCIRConverterFixtureTest {
  private static final String[] METHOD_NAMES = {
      "add", "abs", "sumTo", "pureI32", "pureI64", "pureF64", "normalizedF32",
      "i32ToF64", "i64ToF64", "selectRef", "referenceScore", "nullRef", "switchScore",
      "callStatic"
  };
  private static final String[] METHOD_DESCRIPTORS = {
      "(II)I", "(I)I", "(I)I", "(II)I", "(JI)J", "(DD)D", "(F)F",
      "(I)D", "(J)D", "(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;",
      "(Ljava/lang/Object;Ljava/lang/Object;)I", "(Ljava/lang/Object;)Ljava/lang/Object;", "(I)I",
      "(II)I"
  };
  private static final String[] RETURN_TYPES = {
      "TCIR_TYPE_I32", "TCIR_TYPE_I32", "TCIR_TYPE_I32", "TCIR_TYPE_I32",
      "TCIR_TYPE_I64", "TCIR_TYPE_F64", "TCIR_TYPE_F64", "TCIR_TYPE_F64",
      "TCIR_TYPE_F64", "TCIR_TYPE_REF", "TCIR_TYPE_I32", "TCIR_TYPE_REF", "TCIR_TYPE_I32",
      "TCIR_TYPE_I32"
  };

  @TempDir
  Path workDir;

  @BeforeAll
  static void initByteCodes() throws Exception {
    ByteCode.initClasses();
  }

  @Test
  void converterOutputMatchesNativeFrontendFixture() throws Exception {
    assumeTrue(ToolProvider.getSystemJavaCompiler() != null, "A JDK with javac is required for TCIR fixtures");
    Optional<ModernJavaClassFileFixture> compiled = ModernJavaClassFileFixtures.compileTCIRPocFixture(workDir);
    assumeTrue(compiled.isPresent(), "Current javac cannot target Java 8");

    GlobalConstantPool.init();
    J2TC conversion = new J2TC(new JavaClass(compiled.get().bytes, false), true);
    TCClass converted = conversion.converted;
    assertNotNull(converted);

    String fixture = renderFixture(converted);
    Path fixturePath = findRepositoryRoot().resolve(
        "TotalCrossVM/src/tests/ir/fixtures/tcir_converter_fixtures.h");
    if (Boolean.getBoolean("tcir.updateFixtures") || "true".equals(System.getenv("TCIR_UPDATE_FIXTURES"))) {
      Files.createDirectories(fixturePath.getParent());
      Files.write(fixturePath, fixture.getBytes(StandardCharsets.UTF_8));
    }
    assertTrue(Files.isRegularFile(fixturePath), "Run with -Dtcir.updateFixtures=true to create the fixture");
    assertEquals(fixture, new String(Files.readAllBytes(fixturePath), StandardCharsets.UTF_8));
  }

  private static String renderFixture(TCClass converted) {
    StringBuilder out = new StringBuilder();
    out.append("// Copyright (C) 2026 Amalgam Solucoes em TI Ltda\n")
        .append("//\n")
        .append("// SPDX-License-Identifier: LGPL-2.1-only\n\n")
        .append("// Generated by TCIRConverterFixtureTest from the production J2TC converter.\n\n");

    TCMethod[] methods = new TCMethod[METHOD_NAMES.length];
    for (int index = 0; index < METHOD_NAMES.length; index++) {
      methods[index] = findMethod(converted, METHOD_NAMES[index]);
      appendCodeArray(out, METHOD_NAMES[index], methods[index].code);
      appendLineArray(out, METHOD_NAMES[index], methods[index].code);
      appendParameterArray(out, index);
      appendV64TypeArray(out, METHOD_NAMES[index], methods[index].v64Count);
    }

    out.append("static int tcirResolveConverterFixtureCall(\n")
        .append("   void *user_data, unsigned int symbol, TCIRCallShape *shape)\n")
        .append("{\n")
        .append("   static const TCIRType parameter_types[] = { TCIR_TYPE_I32, TCIR_TYPE_I32 };\n")
        .append("   const TCIRConverterFixture *fixture = (const TCIRConverterFixture *)user_data;\n")
        .append("   if (fixture == (const TCIRConverterFixture *)0 ||\n")
        .append("       fixture->code != tcir_fixture_callStatic_code ||\n")
        .append("       symbol != ((fixture->code[0] >> 8) & 0xfffU))\n")
        .append("      return 0;\n")
        .append("   shape->parameter_count = 2U;\n")
        .append("   shape->returns_value = 1;\n")
        .append("   shape->kind = TCIR_CALL_STATIC;\n")
        .append("   shape->parameter_types = parameter_types;\n")
        .append("   shape->return_type = TCIR_TYPE_I32;\n")
        .append("   shape->owner = \"fixtures.TCIRPoc\";\n")
        .append("   shape->name = \"callTarget\";\n")
        .append("   shape->descriptor = \"(II)I\";\n")
        .append("   return 1;\n")
        .append("}\n\n");

    out.append("static const TCIRConverterFixture tcir_converter_fixtures[] = {\n");
    for (int index = 0; index < methods.length; index++) {
      TCMethod method = methods[index];
      out.append("   { \"fixtures.TCIRPoc.").append(METHOD_NAMES[index]).append(":")
          .append(METHOD_DESCRIPTORS[index]).append("\", tcir_fixture_")
          .append(METHOD_NAMES[index]).append("_code, tcir_fixture_")
          .append(METHOD_NAMES[index]).append("_lines, ")
          .append(method.code.length).append("U, ")
          .append(method.iCount).append("U, ")
          .append(method.oCount).append("U, ")
          .append(method.v64Count).append("U, ")
          .append(method.paramCount).append("U, tcir_fixture_")
          .append(METHOD_NAMES[index]).append("_parameters, ")
          .append(RETURN_TYPES[index])
          .append(", ")
          .append(method.v64Count == 0 ? "(const TCIRType *)0" : "tcir_fixture_"
              + METHOD_NAMES[index] + "_v64_types")
          .append(" },\n");
    }
    out.append("};\n\n")
        .append("#define TCIR_CONVERTER_FIXTURE_COUNT \\\n")
        .append("   (sizeof(tcir_converter_fixtures) / sizeof(tcir_converter_fixtures[0]))\n");
    return out.toString();
  }

  private static TCMethod findMethod(TCClass converted, String name) {
    for (TCMethod method : converted.methods) {
      if (name.equals(GlobalConstantPool.getMethodFieldName(method.cpName))) {
        return method;
      }
    }
    throw new AssertionError("Converted method not found: " + name);
  }

  private static void appendCodeArray(StringBuilder out, String name, TCCode[] code) {
    out.append("static const unsigned int tcir_fixture_").append(name).append("_code[] = {\n   ");
    for (int index = 0; index < code.length; index++) {
      if (index != 0) {
        out.append(index % 4 == 0 ? ",\n   " : ", ");
      }
      out.append(String.format(Locale.ROOT, "0x%08xU", Integer.valueOf(code[index].val)));
    }
    out.append("\n};\n\n");
  }

  private static void appendLineArray(StringBuilder out, String name, TCCode[] code) {
    out.append("static const int tcir_fixture_").append(name).append("_lines[] = {\n   ");
    for (int index = 0; index < code.length; index++) {
      if (index != 0) {
        out.append(index % 12 == 0 ? ",\n   " : ", ");
      }
      out.append(code[index].line);
    }
    out.append("\n};\n\n");
  }

  private static void appendParameterArray(StringBuilder out, int methodIndex) {
    String name = METHOD_NAMES[methodIndex];
    out.append("static const TCIRMethodParameter tcir_fixture_").append(name).append("_parameters[] = {\n");
    if ("pureI64".equals(name)) {
      out.append("   { TCIR_TYPE_I64, TCIR_HOME_V64, 0U },\n")
          .append("   { TCIR_TYPE_I32, TCIR_HOME_I32, 0U }\n");
    } else if ("pureF64".equals(name)) {
      out.append("   { TCIR_TYPE_F64, TCIR_HOME_V64, 0U },\n")
          .append("   { TCIR_TYPE_F64, TCIR_HOME_V64, 1U }\n");
    } else if ("normalizedF32".equals(name)) {
      out.append("   { TCIR_TYPE_F64, TCIR_HOME_V64, 0U }\n");
    } else if ("i32ToF64".equals(name)) {
      out.append("   { TCIR_TYPE_I32, TCIR_HOME_I32, 0U }\n");
    } else if ("i64ToF64".equals(name)) {
      out.append("   { TCIR_TYPE_I64, TCIR_HOME_V64, 0U }\n");
    } else if ("selectRef".equals(name) || "referenceScore".equals(name)) {
      out.append("   { TCIR_TYPE_REF, TCIR_HOME_REF, 0U },\n")
          .append("   { TCIR_TYPE_REF, TCIR_HOME_REF, 1U }\n");
    } else if ("nullRef".equals(name)) {
      out.append("   { TCIR_TYPE_REF, TCIR_HOME_REF, 0U }\n");
    } else {
      int parameterCount = METHOD_DESCRIPTORS[methodIndex].equals("(II)I") ? 2 : 1;
      for (int parameter = 0; parameter < parameterCount; parameter++) {
        out.append("   { TCIR_TYPE_I32, TCIR_HOME_I32, ").append(parameter).append("U }")
            .append(parameter + 1 == parameterCount ? "\n" : ",\n");
      }
    }
    out.append("};\n\n");
  }

  private static void appendV64TypeArray(StringBuilder out, String name, int count) {
    if (count == 0) {
      return;
    }
    out.append("static const TCIRType tcir_fixture_").append(name).append("_v64_types[] = {\n   ");
    for (int index = 0; index < count; index++) {
      if (index != 0) {
        out.append(index % 8 == 0 ? ",\n   " : ", ");
      }
      out.append("pureI64".equals(name) || "i64ToF64".equals(name)
          ? "TCIR_TYPE_I64" : "TCIR_TYPE_F64");
    }
    out.append("\n};\n\n");
  }

  private static Path findRepositoryRoot() {
    Path current = Paths.get("").toAbsolutePath().normalize();
    while (current != null) {
      if (Files.isDirectory(current.resolve("TotalCrossSDK"))
          && Files.isDirectory(current.resolve("TotalCrossVM"))) {
        return current;
      }
      current = current.getParent();
    }
    throw new AssertionError("Cannot locate repository root from " + Paths.get("").toAbsolutePath());
  }
}
