#define NORAS_KEYS \
"5443444B31C7A7D87921D720" /* ADITH Technologies Sp. z o.o. Sp.K.           */ \
"5443444B1E762D5CF49FC4F2" /* Alluviam LLC                                  */ \
"5443444B23DB2EE0A41DC9EA" /* Ampix Software Ltda                           */ \
"5443444B0CC91D63029BB246" /* ARPA SISTEMAS DE INFORMATICA LTDA             */ \
"5443444B217F68A18C5DC7B1" /* ARTNEW TECNOLOGIA EM INFORMATICA LTDA         */ \
"5443444B314891CE3D2DD791" /* BarbaraSoft                                   */ \
"5443444B1F932012FFEDC591" /* BEMATECH S.A.                                 */ \
"5443444BB6C7DDB4574B5C3A" /* CB SISTEMAS LTDA                              */ \
"5443444B7987A7C7452D1FE7" /* Celk Sistemas                                 */ \
"5443444B318C632EC7D1D735" /* CEREAIS BRAMIL LTDA                           */ \
"5443444B19D9C8BAE241BFBE" /* CISS                                          */ \
"5443444B168F1992A96BBCCE" /* Comercial Zaragoza Import e Export LTDA       */ \
"5443444B311691647C9BD702" /* Condor Super Center Ltda                      */ \
"5443444B75D09D1B5DE31B08" /* Cones Informatica Ltda                        */ \
"5443444B959497AE4D4D3B33" /* copel distribuicao sa                         */ \
"5443444B22703B527FADC8A9" /* Criterium Solucoes em Informatica SA          */ \
"5443444B67EDA9C70D2D0DD7" /* DSIN-Desenvolvimento e Solucões em Informática*/ \
"5443444B9253B1B8254138A2" /* EBENEZER PROCESSAMENTO DE DADOS LTDA          */ \
"5443444B09A61FF59A05AF79" /* ECONZ 1971 Ltd                                */ \
"5443444B0FB4EFE8E917B54B" /* EKSPERT Systemy Informatyczne Sp J            */ \
"5443444B2059C555DBA7C6F5" /* Evaldo Fernandes Reu Junior  ME               */ \
"5443444B105149923D6BB6D4" /* FL SOFT TECNOLOGIA LTDA                       */ \
"5443444B5A13AADA6A210022" /* FORD MOTOR COMPANY S. A DE C.V.               */ \
"5443444B0020096C0D93A635" /* GMF Gestao de Medicao e Faturamento Ltda      */ \
"5443444B36C67DBFC33FDC04" /* HH soft                                       */ \
"5443444B054507B58A41AB6C" /* Highsoft Sistemas Ltda ME                     */ \
"5443444B242E552A0CD5CA6E" /* InfoMais Sistemas Ltda                        */ \
"5443444B8EE194D9EE21345D" /* Interativa Integradora de Solucoes Ltda       */ \
"5443444B76267798D3631C6B" /* ISI ENGENHARIA E COMERCIO LTDA                */ \
"5443444B0A2144ABF853B01B" /* LATICINIOS XANDO LTDA                         */ \
"5443444B270AA764D09BCD20" /* Leandro Cesar da Silva                        */ \
"5443444BA02FA7CF4E2D46C0" /* Logical Systems Ltda                          */ \
"5443444B025CDD4F2CADA881" /* Lyncis Programacao e Automacao LTDA           */ \
"5443444B08570B8CB96BAED2" /* Margem VJ Gestao e Tecnologia ltda            */ \
"5443444B005D02AA8053A69C" /* Mobalistic                                    */ \
"5443444B7E8EE99C376324ED" /* Monteiro & Soares Informatica e Serviços LTDA */ \
"5443444B638EBF5A489F09AE" /* OPEN NET INFORMATICA LTDA                     */ \
"5443444B152435DCF921BB4F" /* Parceria Informatica Ltda                     */ \
"5443444B7ECD99EE6A11246F" /* PUMA SISTEMAS DE INFORMATICA LTDA             */ \
"5443444B0ECA370A22F5B482" /* Qualix Solucoes e Servicos                    */ \
"5443444B3A9A87F69105E0ED" /* REDES DESENVOLVIMENTO DE SISTEMAS LTDA        */ \
"5443444B02241DAF804DA85D" /* SG Sistemas de Automacao Ltda                 */ \
"5443444B33FD96C6DC39D92E" /* SINOPSYS  Consultoria e Informatica Ltda      */ \
"5443444B0CB80FB53841B2D5" /* Sovis Servicos em TI Ltda                     */ \
"5443444B425B64821C7DE8DA" /* TEKANN                                        */ \
"5443444B8C98E3C05F3F32D9" /* TGA SISTEMAS DE INFORMATICA LTDA              */ \
"5443444B006712EBF511A60A" /* Tintas Hidracor SA                            */ \
"5443444B0C3D316BBF93B2AB" /* TOP SYSTEM INFORMATICA LTDA                   */ \
"5443444B07845F9F7A5DADF9" /* Vector Informatica Ltda                       */ \
"5443444B070E137AB081AD6C" /* VVS Sistemas                                  */ \
"5443444B5141A1D3BF21F715" /* WMW Systems LTDA                              */ \
"5443444B091A810EB8EFAF30" /* xuxu software ltda                            */ 
