#define NORAS_KEYS \
"5443444B31C7A7D87921D720" /* 843 - ADITH Technologies Sp. z o.o. Sp.K.           */ \
"5443444B1E762D5CF49FC4F2" /* 20  - Alluviam LLC                                  */ \
"5443444B23DB2EE0A41DC9EA" /* 320 - Ampix Software Ltda                           */ \
"5443444B0CC91D63029BB246" /* 384 - ARPA SISTEMAS DE INFORMATICA LTDA             */ \
"5443444B217F68A18C5DC7B1" /* 357 - ARTNEW TECNOLOGIA EM INFORMATICA LTDA         */ \
"5443444B314891CE3D2DD791" /* 610 - BarbaraSoft                                   */ \
"5443444B1F932012FFEDC591" /* 848 - BEMATECH S.A.                                 */ \
"5443444BB6C7DDB4574B5C3A" /* 233 - CB SISTEMAS LTDA                              */ \
"5443444B7987A7C7452D1FE7" /* 844 - Celk Sistemas                                 */ \
"5443444B318C632EC7D1D735" /* 738 - CEREAIS BRAMIL LTDA                           */ \
"5443444B19D9C8BAE241BFBE" /* 827 - CISS                                          */ \
"5443444B168F1992A96BBCCE" /* 248 - Comercial Zaragoza Import e Export LTDA       */ \
"5443444B311691647C9BD702" /* 628 - Condor Super Center Ltda                      */ \
"5443444B75D09D1B5DE31B08" /* 633 - Cones Informatica Ltda                        */ \
"5443444B959497AE4D4D3B33" /* 451 - copel distribuicao sa                         */ \
"5443444B22703B527FADC8A9" /* 652 - Criterium Solucoes em Informatica SA          */ \
"5443444B67EDA9C70D2D0DD7" /* 682 - DSIN-Desenvolvimento e Solucões em Informática*/ \
"5443444B9253B1B8254138A2" /* 841 - EBENEZER PROCESSAMENTO DE DADOS LTDA          */ \
"5443444B09A61FF59A05AF79" /* 415 - ECONZ 1971 Ltd                                */ \
"5443444B0FB4EFE8E917B54B" /* 448 - EKSPERT Systemy Informatyczne Sp J            */ \
"5443444B2059C555DBA7C6F5" /* 428 - Evaldo Fernandes Reu Junior  ME               */ \
"5443444B105149923D6BB6D4" /* 833 - FL SOFT TECNOLOGIA LTDA                       */ \
"5443444B5A13AADA6A210022" /* 748 - FORD MOTOR COMPANY S. A DE C.V.               */ \
"5443444B0020096C0D93A635" /* 375 - GMF Gestao de Medicao e Faturamento Ltda      */ \
"5443444B36C67DBFC33FDC04" /* 790 - HH soft                                       */ \
"5443444B054507B58A41AB6C" /* 704 - Highsoft Sistemas Ltda ME                     */ \
"5443444B242E552A0CD5CA6E" /* 630 - InfoMais Sistemas Ltda                        */ \
"5443444B8EE194D9EE21345D" /* 668 - Interativa Integradora de Solucoes Ltda       */ \
"5443444B76267798D3631C6B" /* 847 - ISI ENGENHARIA E COMERCIO LTDA                */ \
"5443444B0A2144ABF853B01B" /* 823 - LATICINIOS XANDO LTDA                         */ \
"5443444B270AA764D09BCD20" /* 849 - Leandro Cesar da Silva                        */ \
"5443444BA02FA7CF4E2D46C0" /* 201 - Logical Systems Ltda                          */ \
"5443444B025CDD4F2CADA881" /* 422 - Lyncis Programacao e Automacao LTDA           */ \
"5443444B08570B8CB96BAED2" /* 467 - Margem VJ Gestao e Tecnologia ltda            */ \
"5443444B005D02AA8053A69C" /* 339 - Mobalistic                                    */ \
"5443444B7E8EE99C376324ED" /* 759 - Monteiro & Soares Informatica e Serviços LTDA */ \
"5443444B638EBF5A489F09AE" /* 671 - OPEN NET INFORMATICA LTDA                     */ \
"5443444B152435DCF921BB4F" /* 655 - Parceria Informatica Ltda                     */ \
"5443444B7ECD99EE6A11246F" /* 232 - PUMA SISTEMAS DE INFORMATICA LTDA             */ \
"5443444B0ECA370A22F5B482" /* 30  - Qualix Solucoes e Servicos                    */ \
"5443444B3A9A87F69105E0ED" /* 753 - REDES DESENVOLVIMENTO DE SISTEMAS LTDA        */ \
"5443444B02241DAF804DA85D" /* 361 - SG Sistemas de Automacao Ltda                 */ \
"5443444B33FD96C6DC39D92E" /* 660 - SINOPSYS  Consultoria e Informatica Ltda      */ \
"5443444B5A17A93356CB0074" /* 163 - SoftSite Tecnologia LTDA                      */ \
"5443444B0CB80FB53841B2D5" /* 185 - Sovis Servicos em TI Ltda                     */ \
"5443444B425B64821C7DE8DA" /* 283 - TEKANN                                        */ \
"5443444B8C98E3C05F3F32D9" /* 362 - TGA SISTEMAS DE INFORMATICA LTDA              */ \
"5443444B006712EBF511A60A" /* 16  - Tintas Hidracor SA                            */ \
"5443444B0C3D316BBF93B2AB" /* 335 - TOP SYSTEM INFORMATICA LTDA                   */ \
"5443444B07845F9F7A5DADF9" /* 98  - Vector Informatica Ltda                       */ \
"5443444B070E137AB081AD6C" /* 412 - VVS Sistemas                                  */ \
"5443444B5141A1D3BF21F715" /* 270 - WMW Systems LTDA                              */ \
"5443444B091A810EB8EFAF30" /* 205 - xuxu software ltda                            */ \
"5443444BADD4E9F3B30553E8" /* 850 - Enerfocus - Eficiência Energética e Comércio  */ \
"5443444B0D1A9DDA2D21B3DF" /* 459 - Industria e Comercio Copas SA                 */ \
"5443444B24C6CDAB9F53CAB0" /* 796 - Sysbase Informatica Ltda                      */ \
"5443444B13959C9A4D63B99B" /* 930 */                                                 \
"5443444B4A3C533427CBF0B5" /* 383 */ \
"5443444B0E4E6769F195B4A4" /* 204 */ \
"5443444B049519EDBE11AA4A" /* 851 */ 