// Copyright (C) 2026 Amalgam Solucoes em TI Ltda
//
// SPDX-License-Identifier: LGPL-2.1-only

// Generated by TCIRConverterFixtureTest from the production J2TC converter.

static const unsigned int tcir_fixture_add_code[] = {
   0x0100002eU, 0x00000085U
};

static const int tcir_fixture_add_lines[] = {
   4, 4
};

static const TCIRMethodParameter tcir_fixture_add_parameters[] = {
   { TCIR_TYPE_I32, TCIR_HOME_I32, 0U },
   { TCIR_TYPE_I32, TCIR_HOME_I32, 1U }
};

static const unsigned int tcir_fixture_abs_code[] = {
   0x00400076U, 0x00000036U, 0x00000000U, 0x0000027bU,
   0x00000000U, 0x00000085U
};

static const int tcir_fixture_abs_lines[] = {
   7, 7, 7, 7, 7, 7
};

static const TCIRMethodParameter tcir_fixture_abs_parameters[] = {
   { TCIR_TYPE_I32, TCIR_HOME_I32, 0U }
};

static const unsigned int tcir_fixture_sumTo_code[] = {
   0x00000107U, 0x00000207U, 0x00500273U, 0x0201012eU,
   0x00000000U, 0x0001022dU, 0xfffffc7bU, 0x00000185U
};

static const int tcir_fixture_sumTo_lines[] = {
   10, 11, 11, 12, 12, 11, 11, 14
};

static const TCIRMethodParameter tcir_fixture_sumTo_parameters[] = {
   { TCIR_TYPE_I32, TCIR_HOME_I32, 0U }
};

static const unsigned int tcir_fixture_pureI32_code[] = {
   0x00500249U, 0x5a50834fU, 0x00500246U, 0x12308253U,
   0x02030357U, 0x0050024cU, 0xfff08256U, 0x02030257U,
   0x00020301U, 0x00030051U, 0x01000054U, 0x00000301U,
   0x0103024aU, 0x01030047U, 0x00020257U, 0x0103004dU,
   0x00020057U, 0x00000301U, 0x0003017eU, 0x0003007fU,
   0x00010157U, 0x00030080U, 0x00010057U, 0x00000085U
};

static const int tcir_fixture_pureI32_lines[] = {
   17, 17, 17, 17, 17, 17, 17, 17, 17, 20, 20, 20,
   21, 21, 21, 21, 21, 21, 22, 22, 22, 22, 22, 22
};

static const TCIRMethodParameter tcir_fixture_pureI32_parameters[] = {
   { TCIR_TYPE_I32, TCIR_HOME_I32, 0U },
   { TCIR_TYPE_I32, TCIR_HOME_I32, 1U }
};

static const unsigned int tcir_fixture_pureI64_code[] = {
   0x00000181U, 0x0001040fU, 0x0004007cU, 0x00000181U,
   0x0100024bU, 0x01694117U, 0x01020352U, 0x0004007cU,
   0x00000181U, 0x01000248U, 0x0048c117U, 0x01020155U,
   0x01030258U, 0x0004007cU, 0x00000181U, 0x0100014eU,
   0x01020158U, 0x0001020fU, 0x00020234U, 0x0000c117U,
   0x0102013dU, 0x04010139U, 0x0001020fU, 0x0002007cU,
   0x00000181U, 0x01020158U, 0x0001020fU, 0x00300268U,
   0x0002000fU, 0x0000027bU, 0x00000000U, 0x00000087U
};

static const int tcir_fixture_pureI64_lines[] = {
   25, 25, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26,
   26, 26, 26, 26, 26, 26, 29, 29, 29, 29, 29, 30,
   30, 30, 30, 31, 31, 31, 31, 31
};

static const TCIRMethodParameter tcir_fixture_pureI64_parameters[] = {
   { TCIR_TYPE_I64, TCIR_HOME_V64, 0U },
   { TCIR_TYPE_I32, TCIR_HOME_I32, 0U }
};

static const TCIRType tcir_fixture_pureI64_v64_types[] = {
   TCIR_TYPE_I64, TCIR_TYPE_I64, TCIR_TYPE_I64, TCIR_TYPE_I64, TCIR_TYPE_I64
};

static const unsigned int tcir_fixture_pureF64_code[] = {
   0x01000333U, 0x0000c216U, 0x0203023cU, 0x00020038U,
   0x00000000U, 0x00304069U, 0x00000000U, 0x0000027bU,
   0x0001000fU, 0x00000087U
};

static const int tcir_fixture_pureF64_lines[] = {
   34, 34, 34, 34, 34, 35, 35, 35, 35, 35
};

static const TCIRMethodParameter tcir_fixture_pureF64_parameters[] = {
   { TCIR_TYPE_F64, TCIR_HOME_V64, 0U },
   { TCIR_TYPE_F64, TCIR_HOME_V64, 1U }
};

static const TCIRType tcir_fixture_pureF64_v64_types[] = {
   TCIR_TYPE_F64, TCIR_TYPE_F64, TCIR_TYPE_F64, TCIR_TYPE_F64
};

static const unsigned int tcir_fixture_normalizedF32_code[] = {
   0x00000216U, 0x00000116U, 0x00404064U, 0x00004116U,
   0x01020133U, 0x0001020fU, 0x00000116U, 0x0040405dU,
   0x00008116U, 0x01020133U, 0x0001020fU, 0x00000116U,
   0x00404075U, 0x00010116U, 0x01020133U, 0x0001020fU,
   0x00000116U, 0x00404071U, 0x00020116U, 0x01020133U,
   0x0001020fU, 0x00000116U, 0x0040406dU, 0x00040116U,
   0x01020133U, 0x0001020fU, 0x00000116U, 0x00404069U,
   0x00080016U, 0x00020033U, 0x0000020fU, 0x00000287U
};

static const int tcir_fixture_normalizedF32_lines[] = {
   38, 39, 39, 39, 39, 39, 40, 40, 40, 40, 40, 41,
   41, 41, 41, 41, 42, 42, 42, 42, 42, 43, 43, 43,
   43, 43, 44, 44, 44, 44, 44, 45
};

static const TCIRMethodParameter tcir_fixture_normalizedF32_parameters[] = {
   { TCIR_TYPE_F64, TCIR_HOME_V64, 0U }
};

static const TCIRType tcir_fixture_normalizedF32_v64_types[] = {
   TCIR_TYPE_F64, TCIR_TYPE_F64, TCIR_TYPE_F64
};

static const unsigned int tcir_fixture_i32ToF64_code[] = {
   0x00000083U, 0x00000087U
};

static const int tcir_fixture_i32ToF64_lines[] = {
   48, 48
};

static const TCIRMethodParameter tcir_fixture_i32ToF64_parameters[] = {
   { TCIR_TYPE_I32, TCIR_HOME_I32, 0U }
};

static const TCIRType tcir_fixture_i32ToF64_v64_types[] = {
   TCIR_TYPE_F64
};

static const unsigned int tcir_fixture_i64ToF64_code[] = {
   0x00000084U, 0x00000087U
};

static const int tcir_fixture_i64ToF64_lines[] = {
   51, 51
};

static const TCIRMethodParameter tcir_fixture_i64ToF64_parameters[] = {
   { TCIR_TYPE_I64, TCIR_HOME_V64, 0U }
};

static const TCIRType tcir_fixture_i64ToF64_v64_types[] = {
   TCIR_TYPE_I64
};

static const unsigned int tcir_fixture_selectRef_code[] = {
   0x0000022cU, 0x0020005aU, 0x00000209U, 0x00200261U,
   0x00010209U, 0x00000286U
};

static const int tcir_fixture_selectRef_lines[] = {
   54, 55, 55, 56, 56, 57
};

static const TCIRMethodParameter tcir_fixture_selectRef_parameters[] = {
   { TCIR_TYPE_REF, TCIR_HOME_REF, 0U },
   { TCIR_TYPE_REF, TCIR_HOME_REF, 1U }
};

static const unsigned int tcir_fixture_referenceScore_code[] = {
   0x00000007U, 0x00204060U, 0x0001002dU, 0x00204059U,
   0x0002002dU, 0x00200061U, 0x0004002dU, 0x0020005aU,
   0x0008002dU, 0x00000085U
};

static const int tcir_fixture_referenceScore_lines[] = {
   60, 61, 61, 62, 62, 63, 63, 64, 64, 65
};

static const TCIRMethodParameter tcir_fixture_referenceScore_parameters[] = {
   { TCIR_TYPE_REF, TCIR_HOME_REF, 0U },
   { TCIR_TYPE_REF, TCIR_HOME_REF, 1U }
};

static const unsigned int tcir_fixture_nullRef_code[] = {
   0x0000008aU
};

static const int tcir_fixture_nullRef_lines[] = {
   68
};

static const TCIRMethodParameter tcir_fixture_nullRef_parameters[] = {
   { TCIR_TYPE_REF, TCIR_HOME_REF, 0U }
};

static const TCIRConverterFixture tcir_converter_fixtures[] = {
   { "fixtures.TCIRPoc.add:(II)I", tcir_fixture_add_code, tcir_fixture_add_lines, 2U, 2U, 0U, 0U, 2U, tcir_fixture_add_parameters, TCIR_TYPE_I32, (const TCIRType *)0 },
   { "fixtures.TCIRPoc.abs:(I)I", tcir_fixture_abs_code, tcir_fixture_abs_lines, 6U, 1U, 0U, 0U, 1U, tcir_fixture_abs_parameters, TCIR_TYPE_I32, (const TCIRType *)0 },
   { "fixtures.TCIRPoc.sumTo:(I)I", tcir_fixture_sumTo_code, tcir_fixture_sumTo_lines, 8U, 3U, 0U, 0U, 1U, tcir_fixture_sumTo_parameters, TCIR_TYPE_I32, (const TCIRType *)0 },
   { "fixtures.TCIRPoc.pureI32:(II)I", tcir_fixture_pureI32_code, tcir_fixture_pureI32_lines, 24U, 4U, 0U, 0U, 2U, tcir_fixture_pureI32_parameters, TCIR_TYPE_I32, (const TCIRType *)0 },
   { "fixtures.TCIRPoc.pureI64:(JI)J", tcir_fixture_pureI64_code, tcir_fixture_pureI64_lines, 32U, 1U, 0U, 5U, 2U, tcir_fixture_pureI64_parameters, TCIR_TYPE_I64, tcir_fixture_pureI64_v64_types },
   { "fixtures.TCIRPoc.pureF64:(DD)D", tcir_fixture_pureF64_code, tcir_fixture_pureF64_lines, 10U, 0U, 0U, 4U, 2U, tcir_fixture_pureF64_parameters, TCIR_TYPE_F64, tcir_fixture_pureF64_v64_types },
   { "fixtures.TCIRPoc.normalizedF32:(F)F", tcir_fixture_normalizedF32_code, tcir_fixture_normalizedF32_lines, 32U, 0U, 0U, 3U, 1U, tcir_fixture_normalizedF32_parameters, TCIR_TYPE_F64, tcir_fixture_normalizedF32_v64_types },
   { "fixtures.TCIRPoc.i32ToF64:(I)D", tcir_fixture_i32ToF64_code, tcir_fixture_i32ToF64_lines, 2U, 1U, 0U, 1U, 1U, tcir_fixture_i32ToF64_parameters, TCIR_TYPE_F64, tcir_fixture_i32ToF64_v64_types },
   { "fixtures.TCIRPoc.i64ToF64:(J)D", tcir_fixture_i64ToF64_code, tcir_fixture_i64ToF64_lines, 2U, 0U, 0U, 1U, 1U, tcir_fixture_i64ToF64_parameters, TCIR_TYPE_F64, tcir_fixture_i64ToF64_v64_types },
   { "fixtures.TCIRPoc.selectRef:(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;", tcir_fixture_selectRef_code, tcir_fixture_selectRef_lines, 6U, 0U, 3U, 0U, 2U, tcir_fixture_selectRef_parameters, TCIR_TYPE_REF, (const TCIRType *)0 },
   { "fixtures.TCIRPoc.referenceScore:(Ljava/lang/Object;Ljava/lang/Object;)I", tcir_fixture_referenceScore_code, tcir_fixture_referenceScore_lines, 10U, 1U, 2U, 0U, 2U, tcir_fixture_referenceScore_parameters, TCIR_TYPE_I32, (const TCIRType *)0 },
   { "fixtures.TCIRPoc.nullRef:(Ljava/lang/Object;)Ljava/lang/Object;", tcir_fixture_nullRef_code, tcir_fixture_nullRef_lines, 1U, 0U, 1U, 0U, 1U, tcir_fixture_nullRef_parameters, TCIR_TYPE_REF, (const TCIRType *)0 },
};

#define TCIR_CONVERTER_FIXTURE_COUNT \
   (sizeof(tcir_converter_fixtures) / sizeof(tcir_converter_fixtures[0]))
