// Copyright (C) 2026 Amalgam Solucoes em TI Ltda
//
// SPDX-License-Identifier: LGPL-2.1-only

// Generated by TCIRConverterFixtureTest from the production J2TC converter.

static const unsigned int tcir_fixture_add_code[] = {
   0x0100002eU, 0x00000085U
};

static const int tcir_fixture_add_lines[] = {
   4, 4
};

static const unsigned int tcir_fixture_abs_code[] = {
   0x00400076U, 0x00000036U, 0x00000000U, 0x0000027bU,
   0x00000000U, 0x00000085U
};

static const int tcir_fixture_abs_lines[] = {
   7, 7, 7, 7, 7, 7
};

static const unsigned int tcir_fixture_sumTo_code[] = {
   0x00000107U, 0x00000207U, 0x00500273U, 0x0201012eU,
   0x00000000U, 0x0001022dU, 0xfffffc7bU, 0x00000185U
};

static const int tcir_fixture_sumTo_lines[] = {
   10, 11, 11, 12, 12, 11, 11, 14
};

static const TCIRConverterFixture tcir_converter_fixtures[] = {
   { "fixtures.TCIRPoc.add:(II)I", tcir_fixture_add_code, tcir_fixture_add_lines, 2U, 2U, 0U, 0U, 2U },
   { "fixtures.TCIRPoc.abs:(I)I", tcir_fixture_abs_code, tcir_fixture_abs_lines, 6U, 1U, 0U, 0U, 1U },
   { "fixtures.TCIRPoc.sumTo:(I)I", tcir_fixture_sumTo_code, tcir_fixture_sumTo_lines, 8U, 3U, 0U, 0U, 1U },
};
